# Generated by Django 3.1.2 on 2020-11-02 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=1, help_text='Enter number of hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
